repositories {
    maven {
        url = uri "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

loom {
    accessWidenerPath = file("src/main/resources/flora_and_fauna.accesswidener")
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
}

dependencies {
    modCompileOnly "maven.modrinth:sodium:mc$project.minecraft_version-0.5.11"
    modCompileOnly "maven.modrinth:visuality:0.7.4+1.20.5"
    common(project(path: ':core', configuration: 'namedElements')) { transitive false }
}