repositories {
    maven {
        url = uri "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

loom {
    accessWidenerPath = file("src/main/resources/flora_and_fauna.accesswidener")
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
}

dependencies {
    modCompileOnly "maven.modrinth:sodium:mc1.21.10-0.7.3-fabric"
    modCompileOnly "maven.modrinth:visuality:0.7.11+1.21.9"
    modCompileOnly "maven.modrinth:particle-rain:v4-beta.3+1.21.9-fabric"
    common(project(path: ':core', configuration: 'namedElements')) { transitive false }
}